language: rust
sudo: false
git:
  quiet: true

rust:
  - 1.36.0
  - beta
  - nightly

os:
  - linux
  - osx
  #- windows # Works, but already covered by appveyor and takes 7+ minutes (always) vs appveyor's <1 minute.

branches:
  only:
    - staging
    - trying
    - master
    - dev
    - lokathor

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly
  include:
    - { os: linux, rust: 1.36.0,  env: FLAGS=--release }
    #- { os: linux, rust: beta,    env: FLAGS=--release }
    #- { os: linux, rust: nightly, env: FLAGS=--release }

    - { os: osx, rust: 1.36.0,  env: FLAGS=--release }
    #- { os: osx, rust: beta,    env: FLAGS=--release }
    #- { os: osx, rust: nightly, env: FLAGS=--release }

    - { os: linux, rust: 1.36.0,  env: TARGET=wasm32-unknown-unknown }
    #- { os: linux, rust: beta,    env: TARGET=wasm32-unknown-unknown }
    #- { os: linux, rust: nightly, env: TARGET=wasm32-unknown-unknown }
    - { os: linux, rust: 1.36.0,  env: TARGET=wasm32-wasi }
    #- { os: linux, rust: beta,    env: TARGET=wasm32-wasi }
    #- { os: linux, rust: nightly, env: TARGET=wasm32-wasi }

    - { os: linux, rust: 1.36.0,  env: TARGET=aarch64-linux-android }
    #- { os: linux, rust: beta,    env: TARGET=aarch64-linux-android }
    #- { os: linux, rust: nightly, env: TARGET=aarch64-linux-android }
    - { os: linux, rust: 1.36.0,  env: TARGET=armv7-linux-androideabi }
    #- { os: linux, rust: beta,    env: TARGET=armv7-linux-androideabi }
    #- { os: linux, rust: nightly, env: TARGET=armv7-linux-androideabi }
    - { os: linux, rust: 1.36.0,  env: TARGET=i686-linux-android }
    #- { os: linux, rust: beta,    env: TARGET=i686-linux-android }
    #- { os: linux, rust: nightly, env: TARGET=i686-linux-android }
    - { os: linux, rust: 1.36.0,  env: TARGET=x86_64-linux-android }
    #- { os: linux, rust: beta,    env: TARGET=x86_64-linux-android }
    #- { os: linux, rust: nightly, env: TARGET=x86_64-linux-android }
    - { os: linux, rust: 1.36.0,  env: TARGET=arm-unknown-linux-gnueabihf }
    #- { os: linux, rust: beta,    env: TARGET=arm-unknown-linux-gnueabihf }
    #- { os: linux, rust: nightly, env: TARGET=arm-unknown-linux-gnueabihf }
    - { os: linux, rust: 1.36.0,  env: TARGET=armv7-unknown-linux-gnueabihf }
    #- { os: linux, rust: beta,    env: TARGET=armv7-unknown-linux-gnueabihf }
    #- { os: linux, rust: nightly, env: TARGET=armv7-unknown-linux-gnueabihf }
    - { os: linux, rust: 1.36.0,  env: TARGET=thumbv7neon-unknown-linux-gnueabihf }
    #- { os: linux, rust: beta,    env: TARGET=x86_64-linux-android }
    #- { os: linux, rust: nightly, env: TARGET=x86_64-linux-android }

    - { os: osx,   rust: 1.36.0,  env: TARGET=aarch64-apple-ios }
    #- { os: osx,   rust: beta,    env: TARGET=aarch64-apple-ios }
    #- { os: osx,   rust: nightly, env: TARGET=aarch64-apple-ios }
    - { os: osx,   rust: 1.36.0,  env: TARGET=armv7-apple-ios }
    #- { os: osx,   rust: beta,    env: TARGET=armv7-apple-ios }
    #- { os: osx,   rust: nightly, env: TARGET=armv7-apple-ios }
    - { os: osx,   rust: 1.36.0,  env: TARGET=armv7s-apple-ios }
    #- { os: osx,   rust: beta,    env: TARGET=armv7s-apple-ios }
    #- { os: osx,   rust: nightly, env: TARGET=armv7s-apple-ios }
    - { os: osx,   rust: 1.36.0,  env: TARGET=i386-apple-ios }
    #- { os: osx,   rust: beta,    env: TARGET=i386-apple-ios }
    #- { os: osx,   rust: nightly, env: TARGET=i386-apple-ios }
    - { os: osx,   rust: 1.36.0,  env: TARGET=x86_64-apple-ios }
    #- { os: osx,   rust: beta,    env: TARGET=x86_64-apple-ios }
    #- { os: osx,   rust: nightly, env: TARGET=x86_64-apple-ios }

script:
  - pushd scripts
  - ./travis.sh
  - popd

# Configured so we cache cargo-web for WASM unit testing, otherwise it takes forever (13+ minutes) to compile.
# See also https://levans.fr/rust_travis_cache.html
cache:
  directories:
    - $TRAVIS_HOME/.cargo/
    - $TRAVIS_HOME/.rustup/
before_cache:
  - rm -rf "$TRAVIS_HOME/.cargo/registry/src"
