language: rust
sudo: false
git:
  quiet: true

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx

branches:
  only:
    - staging
    - trying
    - master
    - dev
    - lokathor

matrix:
  fast_finish: true
  allow_failures:
  - rust: nightly

script:
  - rustup component add clippy
  - cargo clippy --all --all-features --all-targets -- -D warnings
  - cargo -vv build
  - cargo -vv test
