language: rust
sudo: false
git:
  quiet: true

rust:
  - 1.36.0
  - beta
  - nightly

os:
  - linux
  - osx

branches:
  only:
    - staging
    - trying
    - master
    - dev
    - lokathor

matrix:
  fast_finish: true
  allow_failures:
  - rust: nightly

script:
  - rustup component add clippy
  - cargo clippy
  - cargo build
  - cargo test
