
os: Visual Studio 2015

branches:
  only:
    - staging
    - trying
    - master
    - dev
    - lokathor

matrix:
  fast_finish: true

environment:
  matrix:
    # Stable
    - channel: 1.36.0
      target: i686-pc-windows-msvc
    - channel: 1.36.0
      target: i686-pc-windows-gnu
    - channel: 1.36.0
      target: x86_64-pc-windows-msvc
    - channel: 1.36.0
      target: x86_64-pc-windows-gnu
    # Beta
    - channel: beta
      target: i686-pc-windows-msvc
    - channel: beta
      target: i686-pc-windows-gnu
    - channel: beta
      target: x86_64-pc-windows-msvc
    - channel: beta
      target: x86_64-pc-windows-gnu
    # Nightly is checked only by TravisCI since I honestly don't know how to get
    # this thing to allow for failures with nightly builds.

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -y --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustup component add clippy
  - rustc -vV
  - cargo -vV

# On advice of retep we skip the "build" script phase
build: false

test_script:
  - cargo clippy
  - cargo build
  - cargo test
