
os: Visual Studio 2015

branches:
  only:
    - staging
    - trying
    - master
    - dev
    - lokathor

matrix:
  fast_finish: true

environment:
  matrix:
  # stable
  - host: x86_64-pc-windows-msvc
    targets: aarch64-pc-windows-msvc
    channel: stable
  - host: i686-pc-windows-msvc
    channel: stable
  - host: x86_64-pc-windows-gnu
    channel: stable
  - host: i686-pc-windows-gnu
    channel: stable
  # beta
  - host: x86_64-pc-windows-msvc
    targets: aarch64-pc-windows-msvc
    channel: beta
  - host: i686-pc-windows-msvc
    channel: beta
  - host: x86_64-pc-windows-gnu
    channel: beta
  - host: i686-pc-windows-gnu
    channel: beta
  # nightly
  - host: x86_64-pc-windows-msvc
    targets: aarch64-pc-windows-msvc
    channel: nightly
  - host: i686-pc-windows-msvc
    channel: nightly
  - host: x86_64-pc-windows-gnu
    channel: nightly
  - host: i686-pc-windows-gnu
    channel: nightly
matrix:
  allow_failures:
    - host: x86_64-pc-windows-msvc
      targets: aarch64-pc-windows-msvc
      channel: nightly
    - host: i686-pc-windows-msvc
      channel: nightly
    - host: x86_64-pc-windows-gnu
      channel: nightly
    - host: i686-pc-windows-gnu
      channel: nightly

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -y --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

# On advice of retep we skip the "build" script phase
build: false

test_script:
  - rustup component add clippy
  - cargo clippy --all --all-features --all-targets -- -D warnings
  - cargo -vv build
  - cargo -vv test
